
{{ config(materialized='table') }}

with containers_raw as (
    select
        id,
        "createdById" as createdById,
        "buyOperationId" as buyOperationId,
        "loadingTime" as loadingTime,
        "endTime" as endTime,
        "dateOfLoading" as dateOfLoading,
        status,
        created_at,
        updated_at,
        "allocationId" as allocationId,
        "referenceNumber" as referenceNumber,
        "sealedNumber" as sealedNumber,
        "grossWeight" as grossWeight,
        "tareWeight" as tareWeight,
        "sellOperationId" as sellOperationId,
        "bookingId" as bookingId,
        photos,
        "maximumGrossWeight" as maximumGrossWeight,
        "netWeight" as netWeight,
        "weightSlip" as weightSlip,
        "erpId" as erpId,
        "dateOfSynchronizationToErp" as syncToErpDate,
        "erpRecId" as erpRecId,
        "erpSubRecId" as erpSubRecId,
        eta,
        quantity,
        "quantityUnit" as quantityUnit,
        "isCancelled" as isCancelled,
        "preCarriageLine" as preCarriageLine,
        "shippingLine" as shippingLine,
        "estimatedLogisticCostQuantity" as estimatedLogisticCostQuantity,
        "estimatedLogisticCostVolume" as estimatedLogisticCostVolume,
        "estimatedLogisticCostCurrency" as estimatedLogisticCostCurrency,
        "locationStatus" as locationStatus,
        "etaStatus" as etaStatus,
        "currentEta" as currentEta,
        "originalEta" as originalEta,
        "expectedTransitDays" as expectedTransitDays,
        "currentTransitDays" as currentTransitDays,
        "dateOfDelivery" as dateOfDelivery,
        "trackingEvent" as trackingEvent,
        "actualSailingDate" as actualSailingDate,
        "estimatedSailingDate" as estimatedSailingDate,
        "loadingOtherNumber" as loadingOtherNumber,
        "deliverySlipNumber" as deliverySlipNumber,
        "loadingComment" as loadingComment,
        "loadedOnVessel" as loadedOnVessel,
        "etaPodFinal" as etaPodFinal,
        "actualArrivalPod" as actualArrivalPod,
        "finalEta" as finalEta,
        "reachedDestinationAt" as reachedDestinationAt,
        "podDepartureTime" as podDepartureTime,
        "emptyContainerTime" as emptyContainerTime,
        "deliveryTime" as deliveryTime,
        "deliveryComment" as deliveryComment,
        mode,
        "deliveryDateComment" as deliveryDateComment,
        "loadingDateComment" as loadingDateComment,
        "blNumber" as blNumber,
        "finalMarginQuantity" as finalMarginQuantity,
        "finalMarginCurrency" as finalMarginCurrency,
        "finalMarginVolume" as finalMarginVolume,
        "estimatedMarginQuantity" as estimatedMarginQuantity,
        "estimatedMarginCurrency" as estimatedMarginCurrency,
        "estimatedMarginVolume" as estimatedMarginVolume,
        "generalComment" as generalComment,
        "logisticMaterial" as logisticMaterial,
        "totalFinalMarginQuantity" as totalFinalMarginQuantity,
        "totalEstimatedMarginQuantity" as totalEstimatedMarginQuantity,
        "totalDeliveredTons" as totalDeliveredTons,
        "flagId" as flagId,
        "trackingApiUpdatedAt" as trackingApiUpdatedAt,
        "trackingManualUpdatedAt" as trackingManualUpdatedAt,
        "shipmentComment" as shipmentComment,
        "manualTrackingEvent" as manualTrackingEvent,
        "manualTimingStatus" as manualTimingStatus,
        "manualEmptyContainerTime" as manualEmptyContainerTime,
        "manualLocationStatus" as manualLocationStatus,
        "manualCurrentEta" as manualCurrentEta,
        "manualActualSailingDate" as manualActualSailingDate,
        "manualActualArrivalPod" as manualActualArrivalPod,
        "deliveryOtherNumber" as deliveryOtherNumber,
        "shipmentId" as shipmentId,
        "isPurchaseInvoicingClosed" as isPurchaseInvoicingClosed,
        "isSaleInvoicingClosed" as isSaleInvoicingClosed,
        "pcBookingId" as pcBookingId,
        "tractorNumber" as tractorNumber,
        "estimatedFreightCostQuantity" as estimatedFreightCostQuantity,
        "estimatedFreightCostVolume" as estimatedFreightCostVolume,
        "estimatedFreightCostCurrency" as estimatedFreightCostCurrency,
        "estimatedPreCarriageCostQuantity" as estimatedPreCarriageCostQuantity,
        "estimatedPreCarriageCostVolume" as estimatedPreCarriageCostVolume,
        "estimatedPreCarriageCostCurrency" as estimatedPreCarriageCostCurrency,
        "estimatedPortOfDestination" as estimatedPortOfDestination,
        "estimatedPortOfLoading" as estimatedPortOfLoading,
        "stepperValue" as stepperValue,
        "logisticForwarder" as logisticForwarder,
        "erpStatus" as erpStatus,
        "isPlannedLoading" as isPlannedLoading,
        "isPlannedDelivery" as isPlannedDelivery,
        "isPurchaseInvoicingReopened" as isPurchaseInvoicingReopened,
        "isSaleInvoicingReopened" as isSaleInvoicingReopened,
        harold_number,
        "loadingInspector" as loadingInspector,
        "loadingInspectionDate" as loadingInspectionDate,
        "loadingInspectionCostQuantity" as loadingInspectionCostQuantity,
        "loadingInspectionCostCurrency" as loadingInspectionCostCurrency,
        "loadingInspectionCostVolume" as loadingInspectionCostVolume,
        "loadingType" as loadingType,
        "weightUnit" as weightUnit,
        "gatedInDate" as gatedInDate,
        "stepperValues" as stepperValues,
        "deliveryTareWeightQuantity" as deliveryTareWeightQuantity,
        "deliveryTareWeightVolume" as deliveryTareWeightVolume,
        "deliveryGrossWeightQuantity" as deliveryGrossWeightQuantity,
        "deliveryGrossWeightVolume" as deliveryGrossWeightVolume,
        "isInboundCancelled" as isInboundCancelled,
        "isDeleted" as isDeleted,
        "deliveryType" as deliveryType,
        "warehouseQualityId" as warehouseQualityId,
        "stockpileId" as stockpileId,
        "destinationType" as destinationType,
        "dateOfDeliveryCreation" as dateOfDeliveryCreation,
        inbound_ref_id,
        inbound_ref,
        "logUid" as logUid,
        "logisticCostUpdatedAt" as logisticCostUpdatedAt,
        "isAllocated" as isAllocated,
        "isInboundApproved" as isInboundApproved,
        ---------------------------------- Derived columns ----------------------------------------------
        ROUND(("endTime" - "loadingTime") / ("dateOfLoading" - created_at), 2) as utilizationRate,
        ROUND("grossWeight"/ "maximumGrossWeight", 2) as weightUtilization,
        "endTime" - "loadingTime" as loadingTimeTaken,
        "emptyContainerTime" - "endTime" as unloadingTimeTaken,
        "dateOfDelivery" - "dateOfLoading" as transitTimeTaken,
        "actualArrivalPod" - "finalEta" as delayTime,
        "reachedDestinationAt" - "dateOfLoading" as turnAroundTime

    from {{ source('shipping_data_platform', 'containers') }}
)

select
    *
from containers_raw
