-- models/operations.sql
{{ config(materialized='table') }}

WITH operations_raw AS (
    SELECT
        id,
        agent,
        "agentCommissionQuantity",
        "agentCommissionCurrency",
        "agentCommissionVolume",
        conditionning,
        "createdById",
        "dateOfConfirmation",
        "goalId",
        incoterm,
        mqc,
        "portOfDestination",
        "portOfLoading",
        origin,
        "paymentTerms",
        "isPaymentReceived",
        "priceQuantity",
        "priceCurrency",
        "priceVolume",
        "qualityId",
        "priceCostCurrency",
        "priceCostQuantity",
        "priceCostVolume",
        quantity,
        "quantityVolume",
        "siteId",
        status,
        type,
        "parentOperationId",
        created_at,
        updated_at,
        "referenceNumber",
        "comment",
        "cancellationReason",
        "limitPriceQuantity",
        "limitPriceCurrency",
        "limitPriceVolume",
        "dateOfCreation",
        "dateOfSynchronizationToErp",
        "marginQuantity",
        "marginCurrency",
        "marginVolume",
        "targetCostQuantity",
        "targetCostCurrency",
        "targetCostVolume",
        "destinationId",
        "endDate",
        "poStatus",
        "invoiceStatus",
        "billingEntity",
        division,
        subdivision,
        "erpId",
        "flagId",
        "assignedToId",
        "marketType",
        "contractId",
        "companyId",
        "logisticMaterial",
        "estimatedLogisticCostQuantity",
        "estimatedLogisticCostVolume",
        "estimatedLogisticCostCurrency",
        "shouldBeSentToContact",
        "isPartialShipmentAllowed",
        "placeOfDelivery",
        "soStatus",
        maturity,
        "dateOfLastShared",
        "isWM",
        photos,
        "paymentPercentage",
        "companyReference",
        "otherCostsQuantity",
        "otherCostsCurrency",
        "otherCostsVolume",
        "lastShipmentDate",
        "consigneeId",
        "fxRate",
        "fxSourceCurrency",
        "fxTargetCurrency",
        "fxUpdatedAt",
        "erpStatus",
        "dateOfClosing",
        "isReopened",
        harold_number,
        "minContainerPerShipment",
        "maxContainerPerShipment",
        "releaseType",
        "releaseEvent",
        "shipmentMode",
        "minNumberOfContainers",
        "maxNumberOfContainers",
        "isApproved",
        "adminId",
        "invoiceFollowUpStatus",
        "consigneeCompanyIds",
        "consigneeSiteIds",
        "letterOfCreditId",
        "logUid",
        "isWarehouse",
        "inboundContainerId",
        "dateOfReception",
        "lastArrivalDate",
        "isTransShipmentAllowed",
        ------------ Derived Columns -----------------------------------
        ROUND("priceQuantity" / "limitPriceQuantity", 2) as priceUtilization,
        ROUND("estimatedLogisticCostQuantity" / "priceCostQuantity", 2) as costEfficiency,
        "dateOfConfirmation" - created_at as processingTime,
        "dateOfReception" - created_at as deliveryTime,
        ROUND("marginQuantity" / quantity, 2) as margin

    from {{ source('shipping_data_platform', 'operations') }}
)

SELECT *
FROM operations_raw
